# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

#전체를 workflow라고 함
name: Node.js CI # 액션 파일의 이름

on: # 이 밑에 이벤트가 발생하면 어떻게 해라~, ex) push 이벤트가 발생하면 어떻게 해라
  push: #소스코드 붙인게 push가 되면 저기 아래 jobs를 실행해라, job은 러너로 실행됨, job은 하나 이상의 스텝으로 구성 
    branches: [ "master" ] # branch -> master는 메인 브렌치 master 브랜치에 push 이벤트가 발생하면 job을 실행해라
  pull_request:
    branches: [ "master" ] # master 브랜치에 pull_request 이벤트가 발생하면 job을 실행해라

jobs: 
  build: # build 이벤트 발생

    runs-on: ubuntu-latest # 가장 최신 우분투(운영체제) 러너에서 실행해라

    steps: # 4개의 step으로 구성되어 있음
    - uses: actions/checkout@v4 # 액션 -> 마켓플레이스에 있는 거 활용 가능, checkout -> 우리가 올린 코드를 레포지토리에서 꺼내와라
    - name: Use Node.js 18.x # 두 번째 uses에 이름을 주는 것
      uses: actions/setup-node@v4 # setup-node -> node js 환경을 설정하는 액션
      with: # 파라미터를 주는 것
        node-version: 18.x
        cache: 'npm'
    - run: npm ci # clear(?) install -> 필요한 거 설치해라
    - run: npm test # 자동으로 깃허브에서 실행되는 것
